export const getStyles = (theme) => ({
    launchButton: {
        width: "48px",
        height: "48px",
        borderRadius: "50%",
        backgroundColor: theme.palette.secondary.main,
        boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
        position: "fixed !important",
        bottom: "1.5rem !important",
        right: "1.5rem !important",
        zIndex: 1000,
        padding: 0,
        minWidth: "unset",
        border: "none",
        outline: "none",
        "&:hover": {
            transform: "scale(1.08)"
        },
        "&:active": {
            transform: "scale(0.95)"
        },
        "&:focus-visible": {
            outline: `2px solid ${theme.palette.primary.main}`,
            outlineOffset: "2px",
        },
        "& svg": {
            transition: "transform 0.3s ease",
        },
        "&:hover svg": {
            transform: "rotate(15deg)",
        },
    },
    chatBotMainContainer: {
        position: "fixed !important",
        bottom: "1.5rem !important",
        right: "1.5rem !important",
        zIndex: 2147483646,
        width: "380px",
        height: "500px",
        display: "flex",
        flexDirection: "column",
        alignItems: "flex-end",
        animation: "slideIn 0.3s ease",
        boxSizing: "border-box",
        padding: "2px"
    },
    chatbotBody: {
        width: "100%",
        height: "calc(100% - 60px)",
        display: "flex",
        flexDirection: "column",
        overflow: "hidden",
        border: "1px solid #06314b",
        borderTopLeftRadius: '10px',
        borderTopRightRadius: '10px',
        borderBottomLeftRadius: '0',
        borderBottomRightRadius: '0'
    },
    chatContainerHeader: {
        height: "56px",
        backgroundColor:" #D5EBFF",
        //backgroundColor: theme.palette.primary.light,
        padding: "0.5rem 1rem",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        borderBottom: "1px solid #7191f2",
    },
    botClose: {
        width: "2rem",
        height: "2rem",
        borderRadius: "50%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color: "#000",
        transition: "background 0.2s ease",
        "&:hover": { backgroundColor: "#EAEAEA" },
    },
    chatbotHeading: {
        fontWeight: 600,
        fontSize: "15px",
        lineHeight: "30px",
        color: "#0b2557",
        margin: 0,
    },
    chatContainerBody: {
        flex: 1,
        overflowY: "auto",
        padding: "1rem",
        backgroundColor: theme.palette.secondary.main,
    },
    chatContainerFooter: {
        padding: "1rem",
        backgroundColor: theme.palette.secondary.main,
        borderTop: "1px solid #EDEDED",
    },
    messageStyle: (isUser) => ({
        padding: "0.5rem 0.625rem",
        maxWidth: "calc(100% - 48px)",
        wordWrap: "break-word",
        backgroundColor: isUser ? theme.palette.primary.dark : theme.palette.primary.main,
        borderRadius: "8px",
    }),
    msgSettingContainer: {
        // position: 'absolute',
        // bottom: '-7px',
        // right: '-5px',
        // width: '65px',
        // height: '27px',
        // backgroundColor: '#EEEEEE',
        // borderRadius: '5px',
        // border: `1px solid ${theme?.palette?.action.focus}`,
        display: 'flex',
        justifyContent: 'end',
        alignItems: 'center',
        gap: '6px',
        cursor: 'pointer',
        zIndex: 10,
        // padding: '0 5px'
    },
    textStyle: (isUser) => ({
        fontSize: "14px",
        fontWeight: '400',
        lineHeight: "1.2rem",
        color: isUser ? "#FFFFFF" : "#000000",
        margin: 0,
    }),
    closeBtn: {
        width: "48px",
        height: "48px",
        marginTop: "12px",
        borderRadius: "50%",
        backgroundColor: theme.palette.secondary.main,
        boxShadow: "0 3px 8px rgba(0,0,0,0.25)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        transition: "all 0.2s ease",
        overflow: "hidden",
        aspectRatio: "1 / 1",
        padding: 0,
        minWidth: "unset",
        "&:hover": {
            transform: "scale(1.05)",
        },
    },
    "@global": {
        "@keyframes slideIn": {
            from: { transform: "translateY(20px)", opacity: 0 },
            to: { transform: "translateY(0)", opacity: 1 },
        },
        "@keyframes slideOut": {
            from: { transform: "translateY(0)", opacity: 1 },
            to: { transform: "translateY(20px)", opacity: 0 },
        },
    },
});
